# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'Socially-UIKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Socially-UIKit
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseStorage'
  pod 'FirebaseFirestoreSwift'
  pod 'SDWebImage'
end
