#platform :ios, '9.0'

target 'Socially' do
  # Add the Firebase pod for Google Analytics
  #pod 'FirebaseAnalytics'
  use_frameworks!


  # For Analytics without IDFA collection capability, use this pod instead
  # pod 'Firebase/AnalyticsWithoutAdIdSupport'

  # Add the pods for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseStorage'
end
